sudo: false

language: python
python: 3.6

env:
  global:
  - GH_ORG=aio-libs
  - secure: "jbUg+6rpyI95nNRTw5e1rNgFIGs+FhIBkzgNd+6DpJ3czzF3OPTuO2KVp5sG4PgZbYW0YcjfgTPgGPtwwbWnR+iaaKyE/w5p73gU8a8DBCe03b8mqELbFreMaAiV2DAL6JbNSKMI66xgJfVBIsxUVFt354yq6jtaJw2aypHMhC1D1V+Y2qCpqZH48OYxIfhmqxpPGkxNtv73TEyZjAJKetgRF6/rsCv5bWRLTGy6XTPCoON1Wb7R4dMnyZjgW+RVteEwi4aG+zNaee/yNJL7RQ5EWwkxRFjIV069AtmT1fVRBfKJypYqLLAR8UHNsgZdDgsb8BySAJNxaeJYKomeFnjOlSDYwNkPfVEneWcu8zYAwPjotXyNVaqPekNeXfsuonweL1fnaal5UGR6BrzHjaLmJyiqHhbpgoFnIGKgDYa5R2cVNhwv6nrjne9MF5n+OdgXjIUzBwa9lc8yplMVw5YKoNBcMK8tdjJI52YJC3Bgx62BoV2ywK9Fqch7uThGU/jWOjBfEP2byHQfzqPdk2/dV9IBaV+tRHwCxxejNFLEwL6XYlK96CvCabARaxH7qWD3rXrm6TkY9UZUl1r1kypC/T77nOxEsLoIQgQF8opC2Sit9DN0SbYn0QnWcIP31UqyJGHvbOiuKVzvNce44qmoMetoNflg5cde2p0dl84="

before_install:
- envsubst < .netrc.tmpl > .netrc
- unset GH_TOKEN
install:
- pip install yq
- >-
  curl --netrc-file .netrc -s https://api.github.com/orgs/${GH_ORG}/repos?per_page=9999
- >-
  curl --netrc-file .netrc -s https://api.github.com/orgs/${GH_ORG}/repos?per_page=9999 | jq -r '.[].full_name' > .repos_list
after_install:
- rm -f .netrc
- "echo Repos found:"
- cat .repos_list

script:
- |-
  fail_flag=0
  for repo in `cat .repos_list`
  do
    >&2 echo
    >&2 echo -n Checking ${repo}... ' '
    travis_yml="https://raw.githubusercontent.com/${repo}/master/.travis.yml"
    curl -s "$travis_yml" | yq '' > /dev/null
    check_result=$?
    if [ "$check_result" -eq 0 ]
    then
      status_prefix=
    else
      status_prefix='IN'
      fail_flag=1
    fi
    >&2 echo [ ${status_prefix}VALID ]
  done
  >&2 echo
  >&2 echo Repos checked.
  if [ "$fail_flag" -eq 0 ]
  then
    >&2 echo All repos have valid configs.
  else
    >&2 echo At least one repo has invalid YAML markup in .travis.yml in master
    exit $fail_flag
  fi
