sudo: false

language: python
python: 3.6

env:
  global:
  - GH_ORG=aio-libs

install:
- pip install yq
- >-
  curl -s https://api.github.com/orgs/${GH_ORG}/repos?per_page=9999 | jq -r '.[].full_name' > .repos_list
after_install:
- "echo Repos found:"
- cat .repos_list

script:
- |-
  fail_flag=0
  for repo in `cat .repos_list`
  do
    >&2 echo
    >&2 echo -n Checking ${repo}... ' '
    travis_yml="https://raw.githubusercontent.com/${repo}/master/.travis.yml"
    curl -s "$travis_yml" | yq '' > /dev/null
    check_result=$?
    if [ "$check_result" -eq 0 ]
    then
      status_prefix=
    else
      status_prefix='IN'
      fail_flag=1
    fi
    >&2 echo [ ${status_prefix}VALID ]
  done
  >&2 echo
  >&2 echo Repos checked.
  if [ "$fail_flag" -eq 0 ]
  then
    >&2 echo All repos have valid configs.
  else
    >&2 echo At least one repo has invalid YAML markup in .travis.yml in master
    exit $fail_flag
  fi
