sudo: false

language: generic

env:
  global:
  - GH_ORG=aio-libs

install:
- >-
  curl -s https://api.github.com/orgs/${GH_ORG}/repos?per_page=9999 | tee | jq '.[].full_name' > .repos_list

script:
- skip
